@host=https://localhost:7190

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "ninjaz",
    "lastName" : "speedy",
    "email": "ninjaz.gg@outlook.com",
    "password": "password"
}
